### ISSUE TITLE
texture null

### ISSUE THREAD

**Issue by SilverMantis** [EndLone/MCDE#10]
Hello, I don't know if they are connected or not but I am having these two issues while using the dungeons enchanting mod.

The first one occurs whenever I enter a world, automatically the second I enter the world a message pops up in the chat saying "[MCDEnchantments]: An error occured while loading config. Using defaults. Check out logs for details"
the mod still works even after this message pops up but it seems to have a few things glitched out.
![mcde_glitch_1](https://github.com/EndLone/MCDE/assets/140647107/7ef94994-ffba-4511-ad0a-e67fc090e33a)

The second main issue I'm having is when I go into the runic table to enchant, several (maybe even about half) of the minecraft dungeons enchantments seem to have invalid/null textures.
![mcde_glitch_2](https://github.com/EndLone/MCDE/assets/140647107/60a310b1-dd32-44cd-956a-0471b1b3bf3d)

This is such a cool mod and I hope these glitches can easily and quickly be resolved

**Comment by Iamnotagenius** [comment]
First issue is related to invalid syntax of the config. Did you change it in any way?

Second issue is related to missing textures for enchantments. See [this](https://github.com/EndLone/MCDE#compatibility-with-other-mods).

**Comment by Iamnotagenius** [comment]
The issue with config can be solved by creating a folder named `mcde` in config folder. Sorry for inconvenience.

**Comment by SilverMantis** [comment]
alright, just restarted with the added mcde file in the config and the error message went away, thanks a bunch!

I am still confused on the texture glitch tho

I havent manually added any new enchantments into this mod, the enchants are from the other mc dungeons mods, which in the description of this mod it says it is compatible with. How can I fix this?

**Comment by Iamnotagenius** [comment]
Wait, can you tell from what mod textures are missing? We provide textures only for MCDX (that is, mcdw, mcda and mcdar) enchantments.

**Comment by SilverMantis** [comment]
the glitched textures seem to only be on some of the enchantments from the mcdw mod

**Comment by EndLone** [comment]
The enchanment "Combo" does not exist in any MCDX mods. What happend is in your instance you have a couple other mods and they add other enchantments. You can disable those enchantments from appearing in the config, or add textures to them with a resourcepack.

**Comment by SilverMantis** [comment]
ah, that makes much more sense, I thought they were all normal mc or mcdx enchants

I didn't know that non mcdx mod enchants could appear in the runic table, ill prob just disable those enchants from appearing

Thanks!
