### ISSUE TITLE
Crash with new versions of MCDE

### ISSUE THREAD

**Issue by SilverMantis** [EndLone/MCDE#17]
![image](https://github.com/EndLone/MCDE/assets/140647107/f565a992-2cd3-4d6e-a0f4-d88774d50c3d)

If I use version 1.4.0 or 1.4.1 of MC dungeons enchanting my mincraft crashes after the red loading screen, the version just before those two though (1.3.2) works without any problems, are the recent versions of this mod incompatible with some other mods?

**Comment by EndLone** [comment]
Please provide a full crashlog file. The error that Minecraft Launcher gives players is not enough to understand what is the issue behind this behaviour.

**Comment by SilverMantis** [comment]
ok
[crash-2023-08-16_17.28.53-client.txt](https://github.com/EndLone/MCDE/files/12359940/crash-2023-08-16_17.28.53-client.txt)

**Comment by Iamnotagenius** [comment]
The error you get is really weird. Please, provide the mods you use. Are you playing on a dedicated server or a singleplayer?

**Comment by Iamnotagenius** [comment]
Oh, it seems our mod is definitely not compatible with Create for some reason.

**Comment by SilverMantis** [comment]
damn, is it possible to fix this compatibility issue (since it works on the previous version), and if so do you think you'll be able to fix it for the next version of this mod you guys release?

**Comment by EndLone** [comment]
This issue will be fixed in the next release. Sorry for inconvinience.

**Comment by SilverMantis** [comment]
Awesome, thanks a bunch!
