### ISSUE TITLE
Missing Enchantements

### ISSUE THREAD

**Issue by acquainta** [EndLone/MCDE#20]
Alright i'm the one who posted a comment regarding missing enchantements for bow, crossbow and trident in the 1.19.2 version.

screens:
[Crossbow](https://imgur.com/tFs1qzC)
[Trident](https://imgur.com/95tPNYQ)
[Bow](https://imgur.com/lDGPtwo)

So with that i did some testing and realized that it is caused by the library mod "AutoTag", the MCDE mod alone having no problems at all but once the AutoTag is added it completly messes these items enchantements.

Really wonder why and how it does that but yeah now you know.

**Comment by Iamnotagenius** [comment]
Ah! I didn't know about this mod. The thing is that we use `c:weapons` tag for mcdw weapons to determine if weapon's enchantments (such as sharpness and fire aspect) needed to appear for these items bypassing original restrictions. So this mod adds bow and trident to this tag, making other enchantments to appear.

Current workaround would be to override `c:weapons` tag.
