### ISSUE TITLE
MCDW doesn't work properly with MCDE

### ISSUE THREAD

**Issue by misterSalad** [EndLone/MCDE#21]
If you enchant weapon from MCDW using Runic Table (on screenshot i added fire aspect to swift striker) and it doesnt work (i also checked poisoning and some other enchants), on second and third screen i did the same but with vanilla weapon and weapon from simple swords. all mods I used are in last screen 

![1](https://github.com/EndLone/MCDE/assets/49678575/0778986a-3545-46d8-aeaa-5b00f9b0b29a)
![1-1](https://github.com/EndLone/MCDE/assets/49678575/77d73c0a-3d9a-4d62-b658-af3969ffb4c8)
![2](https://github.com/EndLone/MCDE/assets/49678575/c7caef78-c69c-414c-a009-16d95934f654)
![2-2](https://github.com/EndLone/MCDE/assets/49678575/f8e808c8-6073-4aca-a54e-dc5ad0ad5e99)
![3](https://github.com/EndLone/MCDE/assets/49678575/cb79219c-91f5-4c69-81ea-0cd8e901de0f)
![3-3](https://github.com/EndLone/MCDE/assets/49678575/d0213f2a-59e1-4965-8016-0aecb5f57c43)

![7](https://github.com/EndLone/MCDE/assets/49678575/76e12bc1-dd4d-4342-a3d1-d189e4049068)

**Comment by Iamnotagenius** [comment]
The issue is on the MCDW's side (my suspicion is its EnchantGiver's fault) so this wouldn't be worked on in here/
