### ISSUE TITLE
Crash When Rerolling in bench

### ISSUE THREAD

**Issue by Lepommejamez** [EndLone/MCDE#22]
First, I tried rerolling enchantments with lapis, to no avail. When clicking the enchant, nothing happened. Then i tried with echo shards, and a new reroll button appeared (I didn't know that existed, I used to play with a version where you couldn't use echo shards). Then I pressed that, and nothing happened. I then tried clicking on a specific enchantment to reroll, and the game crashed. Here is the crash report:
[crash-2023-10-17_14.09.55-server.txt](https://github.com/EndLone/MCDE/files/12942348/crash-2023-10-17_14.09.55-server.txt)

**Comment by EndLone** [comment]
Thank you for pointing out this issue, we're already looking into it and what could be done to fix it.
