### ISSUE TITLE
Enchantments for Spell Weapons from Spell Engine based mods don't show up, aside from Spell Infinity

### ISSUE THREAD

**Issue by cleannrooster** [EndLone/MCDE#29]
As the title says, I have spent quite a while rerolling in creative with things such as staves and have never got enchantments such as Spell Power or Spell Haste. Strangely Spell infinity shows up though.

EDIT: This seems to happen with damage enchants for armor such as sunfire as well.

**Comment by Iamnotagenius** [comment]
What armors and staves were you trying to enchant? You need certain corresponding powers on the gear to enchant it. So maybe the gear wasn't enchantable in the first place.

**Comment by Iamnotagenius** [comment]
I was able to get the Spell Haste, Spell Power and Spell Infinity on the wands from the [Wizards](https://modrinth.com/mod/wizards) mod so I'm waiting for your answer.

**Comment by cleannrooster** [comment]
I was using Staves at the time I believe, but I consulted with Daedalus and he explained that the recent rewriting for Spell Power enchantments may have caused some problems. I may have been attempting to do it with Spellblade and Such third party weapons so that probably has something to do with it too.

**Comment by cleannrooster** [comment]
Once I am able to I will add tags for Spellblade weapons and armors to make them compatible hopefully and get back to you regarding this.

**Comment by cleannrooster** [comment]
The Spellblade weapons and Armors should be compatible now-- I would like to also get back to you with some pixel art for Spell Engine enchants if you would like!
