### ISSUE TITLE
don't  know how to config mc dungeon enchanting mod

### ISSUE THREAD

**Issue by JustTakeda** [EndLone/MCDE#32]
hi, I installed mc dungeon enchanting mod and I don't know how to config it to use enchanting table vanila at the same time as runic table and roll bench, can someone instruct me how to config that?  ty

**Comment by Iamnotagenius** [comment]
The config file is generated and put into `config/mcde/config.json` file in your `.minecraft` folder. The option you're looking for is `allowEnchantingTable`. The config file itself is extensively documented so it shouldn't be hard to find the right option.
