### ISSUE TITLE
[1.20.1] [ver.1.5.7 and previous] Crashes game when interacting with UI / UI does not work 

### ISSUE THREAD

**Issue by MihanDeNoob** [EndLone/MCDE#33]
This is has to be some mod incompatibility but im clueless as to what it could be

The only two mods affecting UI is Exordium and Charm Forked (inventory sorting button), both of which i disabled while testing. 

(Dont mind them being enabled in the log, log with them disabled failed to generate for some reason but it was the same crash) full log: https://mclo.gs/CJWaU7p

crash log: https://mclo.gs/nooDCcM

**Comment by Iamnotagenius** [comment]
judging by the logs you're using 1.4.1-1.20 version, which is really old, try with a newest one, reopen the issue if you encounter a crash with a newest version
