### ISSUE TITLE
[1.20.1] UI does not work

### ISSUE THREAD

**Issue by MihanDeNoob** [EndLone/MCDE#34]
Using latest version of the mod.  I can place items but nothing happens. 
Any clues as to what may cause this? 

Here is the log: https://mclo.gs/CJWaU7p 
Mod version in the log is outdated but the issue is the same, minus crashing when interacting with UI

**Comment by Iamnotagenius** [comment]
the old logs wouldn't help. Please, provide a log with the newest version (I uploaded one just now).
