### ISSUE TITLE
[1.20.1]  UI does not work. Latest and previous mod versions. 

### ISSUE THREAD

**Issue by MihanDeNoob** [EndLone/MCDE#35]
full log: https://mclo.gs/OX7AkIL#L4787  

https://github.com/user-attachments/assets/f813e51d-b9a0-42a7-be54-8f26f210f0b0

This has to be some mod incompatibility but i dont understand the error logs about mcde

**Comment by Iamnotagenius** [comment]
Please, could you provide a modpack you're using?

**Comment by MihanDeNoob** [comment]
Thats a personal modpack im using. Im an experienced user, but im completely clueless as to what mod could cause this issue. 
The only two mods i have effecting ui are [Exordium](https://modrinth.com/mod/exordium) and [Charm Forked](https://www.curseforge.com/minecraft/mc-mods/charm-forked) (item sorter button, but ive disabled that feature), ive tested without them but the mcde errors were the same, so its not them.

**Comment by MihanDeNoob** [comment]
So the only way to test it is to slowly, one by one, remove mods? Yeah, thats gonna take a while with 370 jar files XD well, not really 370 since i can tell which mods are for sure not causing this, but still, do you know what should i look for judging by the mcde errors in the log?

**Comment by Iamnotagenius** [comment]
The real reason could be that one of the advancement's configs are broken. It crashed while trying to get some advancement's progress. So check these out as well. I'll close the issue when this would be confirmed and a patch would be made to mitigate this.

**Comment by Iamnotagenius** [comment]
Yep, so when the advancement is broken or doesn't exist there's an error which causes this bug. Alright, this mod is more than a year old and you're the first one that encountered this bug. Fascinating.

**Comment by MihanDeNoob** [comment]
Yup, issue has been fixed! I wonder what causes the advancements to brake, because i have similar issue with other mods advancements having errors but without any real issue.
