### ISSUE TITLE
[Question] Will all MC Dungeons Mod Series be updated to 1.21.X?

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [EndLone/MCDE#38]
Hello!
Sorry for disturbing via Issues, but I didn't find any better platform for communicating about MC Dungeons Mods:
Will all MC Dungeons Mod Series be updated to 1.21.X?

Thanks for the Answer in advance!

P. S. I saw in there 1.21 Branch, but I want to be sure about MC Dungeons Mods being updated to 1.21. If possible, even know the precise ETA.

**Comment by Iamnotagenius** [comment]
Sorry for crickets. The update is planned (all work is on 1.21 branch). I hope I will have the time to complete the migration during new year holidays.
