### ISSUE TITLE
Improve enchantment compatibility in slots

### ISSUE THREAD

**Issue by Iamnotagenius** [EndLone/MCDE#4]
So, right now, the generation of new enchantments works like this:
1. Remove from pool every enchantment associated with the item (even the choices)
2. if pool is empty - cant generate
3. if not - take any enchantment from the pool
For roll bench it works okay (you just cant reroll). As for gilding, it might work better
since a player can't reroll enchantments, it should still be possible to gild an item as
there are still non-used enchantments (and can't be used since already choosed enchantments can't be rerolled).

Also, the generation of slots should respect isCompatible method (of course, it will be configurable).

**Comment by fzzyhmstrs** [comment]
One suggestion I have for improving proper selection per the modders wishes would be to switch `EnchantmentTarget.isAcceptableItem` to `Enchantment.isAcceptableItem`. This would capture custom acceptance checks that general target doesn't capture. The default impl of `Enchantment.isAcceptableItem` is simply returning `EnchantmentTarget.isAcceptableItem` anyways
