### ISSUE TITLE
Replay Mod compatibiliy

### ISSUE THREAD

**Issue by xlifi** [EndLone/MCDE#5]
Logs: https://mclo.gs/SSGdCqH
If any additional info is needed, I can provide it. Though logs should have everything

**Comment by Iamnotagenius** [comment]
It seems block entities in your world have the old ids (I changed namespace from `mcd_enchantments` to `mcde` in 1.2.0).
So try creating a new world and see if it crashes or try to replace blocks in existing world.

**Comment by xlifi** [comment]
I figured I'd launch a server and try it there. Server logs: https://mclo.gs/42BxwdN
Client logs (only part when I'm on server): https://mclo.gs/K56fNPm

Here's [all my mods](https://cdn.discordapp.com/attachments/1096696773214490727/1133929894435377264/mods.zip)

Also modrinth link in readme.md is incorrect

**Comment by xlifi** [comment]
Removing Replay Mod fixes the issue

**Comment by Iamnotagenius** [comment]
Alright, I'll test your modpack and see if my mod causes any trouble. If not, I will close this. But I don't see in logs that my mod crashes the game.
